### ISSUE TITLE
Script change

### ISSUE THREAD

**Issue by leandrocombr** [dealfonso/sapp#1]
Hi,

Can I hire you to adapt the script to my needs?

**Comment by dealfonso** [comment]
Hi,

In first place, thank you for your interest in SAPP.

If you are interested in general questions about SAPP or requesting general features, feel free to open issues requesting for help as they may also help others.

If you have specific modifications or dedicated programming, please contact me through linked in (my linked in profile is on my GitHub profile).

Regards.
