### ISSUE TITLE
Error on read some PDF：Invalid string

### ISSUE THREAD

**Issue by lemsn** [dealfonso/sapp#10]
Hello Carlos!

![图片](https://user-images.githubusercontent.com/9290824/140262045-6f344350-3737-4ec4-b588-1a7432d4970d.png)

Examples follows attaching :
[TestPDF.pdf](https://github.com/dealfonso/sapp/files/7472489/TestPDF.pdf)

**Comment by dealfonso** [comment]
Hi,

comit #c767544a6de84313fb9ebcbf3df9e6ce7670b16e seems to correct this bug.

Thank you for reporting!

**Comment by lemsn** [comment]
Very good. Thank you for your contribution.

The following are the results of my tests:

The previous file can be read, but there is still a problem, some files are still not read properly,
Can you revert to the previous version?



![image](https://user-images.githubusercontent.com/9290824/140610354-3ed178f4-5a7b-42cf-a3e4-0cc7c5c1f40e.png)


attaching :

[94cfd0d2-4523-49e3-887b-b10bfd440b50.pdf](https://github.com/dealfonso/sapp/files/7490484/94cfd0d2-4523-49e3-887b-b10bfd440b50.pdf)

**Comment by dealfonso** [comment]
Hi,

a bit late, but corrected the support for escaped parenthesis in commit 2e4d2d72fb4b41026e8093b9e9fd8cc990fa43e4
