### ISSUE TITLE
Feature: Signature appearance as pdf object or html

### ISSUE THREAD

**Issue by kczereczon** [dealfonso/sapp#15]
Is possible to make the signature appearance just the pdf object instead of image or html?

**Comment by dealfonso** [comment]
hi, I cannot understand exactly what you mean, but if you refer to including the signature without any image, you have an example called `pdfsign.php` that includes a non-visible signature for a PDF file (it just signs the document and does not include any image). Please try it and tell me if it solves your problem.

**Comment by kczereczon** [comment]
No i mean additional extension for signature appearance at this moment we are able to sign pdf with image, I found out that one of commercial solutions represent signature appearance as pdf object (that is draggable) it would be cool feature in this library

**Comment by dealfonso** [comment]
I have tried using a PDF document as a signature appearance, but it seems that in the end, it is not an embedded PDF document in the other PDF document; instead, it seems a snapshot of one of the pages of the document used as a signature appearance. This is the first thought, and I'll need to check it again. Could you please confirm that the resulting signature contains an embedded PDF document?
