### ISSUE TITLE
Error opening a pdf in sapp - PDFDoc.php:755: generating xref using classic xref...trailer

### ISSUE THREAD

**Issue by MoisesAlvesSousa** [dealfonso/sapp#16]
[testdoc-signed.pdf](https://github.com/dealfonso/sapp/files/8781887/testdoc-signed.pdf)

PS C:\wamp64\www\PROJETOSITE\2022\assinaturaDigital\assinaturaSAPP> php pdfsigni.php examples/testdoc.pdf "https://www.google.es/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png" JOSIVAN.pfx > testdoc-signed.pdf
Password: 'stty' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
805493
'stty' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

Debug info at C:\wamp64\www\PROJETOSITE\2022\assinaturaDigital\assinaturaSAPP\src\PDFDoc.php:755: generating xref using classic xref...trailer

**Comment by MoisesAlvesSousa** [comment]
I'm new to PHP.

I'm creating an application to digitally sign PDF more than once.

This variable $docsigned, is there any method already created to save it in a PDF file?

**Comment by MoisesAlvesSousa** [comment]
I'm already developing my application with sapp.
A doubt as I can insert the function set_metadata in my file.
How can I call her.

**Comment by MoisesAlvesSousa** [comment]
I have a file with several pages in pdf, I wanted to put the graphic signature on each one as
$obj->set_signature_appearance(0, [ $p_x, $p_y, $p_x + $i_w, $p_y + $i_h ], $image);
I created a loop but it is only on the last page.
Would you like to do that?

**Comment by dealfonso** [comment]
Hi,

from your last message, I see that you have managed to write the file (e.g. using `file_put_contents`).

On your last query... in a PDF file, one signature can only have one appearance. So, when you use `set_signature_appearance` at different times, the position is updated. In case you want multiple graphics, you can sign the document multiple times, but I find that it has no sense: signing the document is useful to keep the integrity of the document. So signing the document multiple times, would mean to keep the same integrity multiple times.

If you simply want to add multiple graphics to a document and then signing it, it is a different approach, but keep in mind that in that case you sign a different document than the original one.

**Comment by MoisesAlvesSousa** [comment]
Good Morning
So I still can't put the method information in the signature.

public function set_metadata(){
     $name
     $reason
     $location
     $contact
}
How could I enter this information?

**Comment by dealfonso** [comment]
At this moment, the metadata is not included in the final document.
