### ISSUE TITLE
Parsing previously signed PDF throws "Invalid token" exception in Parser

### ISSUE THREAD

**Issue by micah1701** [dealfonso/sapp#17]
admittedly, I do not fully understand the underlying object structure of PDF, so feel free to take my "issue" with a grain of salt.
I created a signed (with image) PDF, based on the pdfsigni.php example.  It worked and I was able to generate a signed PDF.  Very cool, I might add!

However, when I attempt to run the same script on the newly generated PDF, it dies out on line 350 of the PDFObjectParser (which is the default switch case when there is an invalid token.)  For what its worth, my "Invalid token" (eg $this->_tt) is "5."  I don't really know what that means though, LOL

Any thoughts on what silly and obvious thing I am missing here?  Thanks!

**Comment by dealfonso** [comment]
Hi,

thank you for reporting. It would be nice if you could provide an example of this error. It seems that it has to do with issue #10

**Comment by micah1701** [comment]
Thanks for your quick reply.  I did a little bit more testing and, using your `examples/testdoc.pdf` worked fine without the given error so, there is presumably something wonky about my source PDF.

Here's my test repo: https://github.com/micah1701/sapp

This works:
in [myapp/index.php](https://github.com/micah1701/sapp/blob/main/myapp/index.php) when using the source document "examples/testdoc.pdf" I am able to create a signed pdf and save it to "files/testdoc1.pdf"  I then change the source document to files/testdoc1.pdf" and am able to create a second signed pdf, and save it to "files/testdoc2.pdf"

This also works:
in [myapp/test.php](https://github.com/micah1701/sapp/blob/main/myapp/test.php) (which is a clone of index.php) using the source document "examples/LAB.pdf" I am able to create a signed pdf and save it to "files/LAB1.pdf"

BUT:
when I change the source document to files/LAB1.pdf (the signed version of my example pdf) and attempt to create a second signed PDF, that is when I get the previously mentioned error.

**Comment by micah1701** [comment]
That absolutely worked!  Thank you for taking the time to maintain this valuable repo.
Cheers
