### ISSUE TITLE
Undefined constant "ddn\\sapp\\helpers\\STDERR\" when running outside CLI

### ISSUE THREAD

**Issue by iMusicJJ** [dealfonso/sapp#18]
This happens when the script is run as part of a PHP-program, and not as a CLI script.

The particular instance that I am running into is at PDFDoc:755

`p_debug("generating xref using classic xref...trailer");`

**Comment by raimon-segura** [comment]
Hi!,

I could workaround this adding `if(!defined('STDERR')) define('STDERR', fopen('php://stderr', 'wb'));` just before the `PDFDoc::from_string` call, hope this helps!

**Comment by dealfonso** [comment]
Hi,

commit f1c548c213ebfe8eef5295e15390018aeec77cbb solves this issue.

Thank you @raimon-segura for the hint.

@iMusicJJ could you please check it?

**Comment by raimon-segura** [comment]
@dealfonso thanks to you for your great work with this project! ...best solution to sign pdf :D
