### ISSUE TITLE
"PDFDoc->to_pdf_file_s" with rebuild parameter to "true" cannot be signed by multiple certificates

### ISSUE THREAD

**Issue by raimon-segura** [dealfonso/sapp#22]
Hi!,

I've noticed that if I set "$rebuild" to true in PDFDoc::to_pdf_file_s($rebuild = false) the pdf cannot be signed by multiple certificates, I've followed " _generate_signature_in_document()" doc... 

With "$rebuild = false" all works well, so I'm not sure if I have to set to true, or false, ...or maybe true only in the last call... 

which is better?

thanks!

**Comment by dealfonso** [comment]
Hi,

rebuilding a PDF document means removing any element in the document and adding it again. This is useful to optimize documents, but this also means that the document is modified, so the properties of the signature are lost.

So, do not use `$rebuild = true` unless the document is not signed.

Regards

**Comment by raimon-segura** [comment]
Thanks!..

so, as a resume its ok to rebuild the first time, right?

I've tested and it works well, rebuilding only the first time... it saves 1kb haha, from 441,4Kb to 440,6Kb.. But I'm thinking to not rebuild.


Many thanks!
