### ISSUE TITLE
Composer install warning => "Class ddn\sapp\helpers\UUID located in ./vendor/ddn/sapp/src/helpers/uuid.php does not comply with psr-4 autoloading standard. Skipping."

### ISSUE THREAD

**Issue by raimon-segura** [dealfonso/sapp#24]
Hi!,

I've found a warning message when I install this project using composer, but all works well ...it says:

`Class ddn\sapp\helpers\UUID located in ./vendor/ddn/sapp/src/helpers/uuid.php does not comply with psr-4 autoloading standard. Skipping.`

Not sure if its good or bad :D .. what I do to use it is `use ddn\sapp\PDFDoc;` at the beginning of php file

Thanks!

**Comment by dealfonso** [comment]
Hi,

latest commit changes the name of the file to comply with psr-4. @raimon-segura Could you please check it?

Regards

**Comment by raimon-segura** [comment]
Hi!,

Just reset & installed all composer packages again, but unfortunately it says the same thing:
`Class ddn\sapp\helpers\UUID located in ./vendor/ddn/sapp/src/helpers/uuid.php does not comply with psr-4 autoloading standard. Skipping.`

... I'm using `Composer version 2.3.10 2022-07-13 15:48:23` within this Yii2 project template => `https://github.com/yiisoft/yii2-app-advanced` , maybe its due to this reason.

Thanks!

**Comment by dealfonso** [comment]
Hi, 

as of the message `Class ddn\sapp\helpers\UUID located in ./vendor/ddn/sapp/src/helpers/uuid.php does not comply with psr-4 autoloading standard. Skipping`, it seems that you are not using the latest version (1.1.0), as the file's name in this version is in capital letters.

Could you please try upgrading sapp?

**Comment by raimon-segura** [comment]
HI!,

You are right, it seems I have un force update someway because there is the git-hash reference in composer.lock 
`"reference": "a3eec1e6cc437157bc7576ae123419b9b578c338"` ..let me check again.. thanks!

**Comment by raimon-segura** [comment]
Hi!,

Now it works, I have to do `composer update ddn/sapp` to update git hash package in composer.lock ..Also, i've checked my pdf and they are well too!

thanks!
