### ISSUE TITLE
Get signatures count method

### ISSUE THREAD

**Issue by erikn69** [dealfonso/sapp#29]
I'm trying to add multiple signature images incrementally, there is a way to count previous signatures (for avoid overlapping images recalculating position on base of signature count)
Like 
https://github.com/dealfonso/sapp/blob/01acefd42ce5dfb4d572b76db2b1871270991abe/src/PDFDoc.php#L89-L91

For example
```php
public function get_signature_count() { 
     return count($this->_signatures); 
} 
```

**Comment by dealfonso** [comment]
Currently, there is no way to calculate the number of signatures. 

Assuming that a signature makes a new document version, there would be a mechanism that would consist of counting the number of _xref tables_ (i.e. the depth of the document). The current version of sapp takes into account such depth in functions `get_xref_*` but does not store the depth of the document. Maybe you can try to store it and see if that meets your requirements. If so, please create a pull request.
