### ISSUE TITLE
error in the second signature

### ISSUE THREAD

**Issue by aespinozafa** [dealfonso/sapp#3]
Hola , excelente proyecto , 
ayudame con algo, no se si lo estoy haciendo bien . 

Intento tener una segunda firma en el documento que genere

php pdfsign.php testdoc-signed.pdf fq.p12 > testdoc-resigned.pdf

y me sale este error
-----------------------------------------------------------------------------------------------
Hello, excellent project,
help me with something, I don't know if I'm doing it right.

I try to have a second signature in the document that it generates

php pdfsign.php testdoc-signed.pdf fq.p12> testdoc-resigned.pdf
--------------------------------------------------------------------------------------------------

Error info at C:\laragon\www\sapp\src\PDFUtilFnc.php:377: PDF version string not found
failed to parse file testdoc-signed.pdf

**Comment by dealfonso** [comment]
Hola, 

el documento testdoc-signed.pdf se puede abrir con acrobat reader?

**Comment by aespinozafa** [comment]
hola, 
te comento que en la primera firma lo hace sin ningún inconveniente,, incluso el archivo firmado se puede ver en adobe Reader, pero cuando ya intento firmar con un segundo usuario es donde se cuelga.

**Comment by dealfonso** [comment]
Podrías poner el archivo firmado como adjunto?

**Comment by dealfonso** [comment]
> hola,
> te comento que en la primera firma lo hace sin ningún inconveniente,, incluso el archivo firmado se puede ver en adobe Reader, pero cuando ya intento firmar con un segundo usuario es donde se cuelga.

ha podido solucionar el problema? si no es así, puede adjuntar el PDF que le provoca el error?

**Comment by dealfonso** [comment]
Hola,

ese documento no está soportado... es raro incluso que haya funcionado la primera firma. El motivo es que tiene objetos PDF que actualmente no soporta sapp. Es algo que está pendiente de resolver... intentaré arreglarlo pronto.

**Comment by krefects** [comment]
Você precisa converter o arquivo usando o PDFtk, após isso poderá inserir quantas assinaturas quiser.

shell_exec('pdftk '.$file.' cat output '.$fileSaveConverted.'');

**Comment by dealfonso** [comment]
Al convertir el archivo, en realidad se estará modificando el documento original. El resultado es un PDF *distinto* al original. Si el archivo se compara con el original, no será válido. Si sólo se quiere tener un documento aparentemente igual, esa es una solución pero repito: el convertido es un documento PDF distinto al original.
