### ISSUE TITLE
Can it save changes incrementally?

### ISSUE THREAD

**Issue by kmgbarroga** [dealfonso/sapp#43]
Good day, I am reaching out to ask if it is possible to add images to pdf and save the changes incrementally. Is that possible with this library?
Your response will be highly appreciated. Thank you!

**Comment by dealfonso** [comment]
hi, not at this moment. I have a class `PDFDocWithContents` in which there is a function called `add_image`, but it still needs work. Sorry.

**Comment by parallels999** [comment]
@kmgbarroga did you try setasign/fpdi?

**Comment by dealfonso** [comment]
> @kmgbarroga did you try setasign/fpdi?

does FPDI manage incremental docs?

**Comment by kmgbarroga** [comment]
> > @kmgbarroga did you try setasign/fpdi?
> 
> does FPDI manage incremental docs?

From what I have seen so far, they don't. Just $pdf->Output();, that's all there is.

**Comment by parallels999** [comment]
You can import pages, and and changes incrementally

**Comment by parallels999** [comment]
> but there is another meaning of "incremental" in pdf, it means that I could roll back to the previously committed change. 

Ok, no idea about that

**Comment by dealfonso** [comment]
An incremental PDF document is a differential document. The final PDF file contains the original version along with changes; then, if more changes are made, you can add another block of differences. That is how signature works: there is a document, and you add an incremental document that only contains the signature; then it is possible to check whether the document has been changed or not using a hash for the first part.

Using this mechanism, it is possible to keep track of any changes and revert to prior versions.

It is possible to read the PDF document with any text reader and you'll notice multiple `%%EOF` blocks if the document is incremental.
