### ISSUE TITLE
Can I use crt file instead of p12?

### ISSUE THREAD

**Issue by Veiote** [dealfonso/sapp#45]
can i use crt file like in tcpdf?

**Comment by erikn69** [comment]
https://github.com/dealfonso/sapp/blob/61960ae449be7b86d47a625bab625b26db8e6ee3/src/PDFDoc.php#L281-L287

**Comment by parallels999** [comment]
@dealfonso This does not seem like a issue, and it is also inactive, must be closed

**Comment by dealfonso** [comment]
Hi, i'd prefer that the owner closes the issues. If he/she does not close the issue, I usually close them after some time.

**Comment by parallels999** [comment]
This wastes the time of someone who perhaps comes to help when they see active issues, and also the user has been inactive for a long time, possibly opening eventual issues and never reviewing the responses.
