### ISSUE TITLE
Issue with Digital Signature Validation

### ISSUE THREAD

**Issue by Abdulazeezvp** [dealfonso/sapp#46]
I have recently encountered an issue with the digital signature validation of file.pdf. Upon checking the signature information, I found that there is a "Digest Mismatch" error, which indicates that the computed digest of the signed ranges does not match the actual digest of the file.

Signature Info of: file.pdf
Signature #1:
  - Signer Certificate Common Name: test
  - Signer full Distinguished Name: CN=test,OU=Test,O=test,L=Kochi,ST=Kerala,C=IN
  - Signing Time: Mar 15 2023 18:24:49
  - Signing Hash Algorithm: SHA-256
  - Signature Type: adbe.pkcs7.detached
  - Signed Ranges: [0 - 49517], [61261 - 61606]
  - Not total document signed
  - Signature Validation: Digest Mismatch.
I believe this is abnormal and could indicate that the file has been tampered with or corrupted. I would appreciate it if someone could look into this issue and provide guidance on how to resolve it.

**Comment by Abdulazeezvp** [comment]
[original document(before signing)](https://github.com/dealfonso/sapp/files/10980876/sample.pdf)
[signed pdf](https://github.com/dealfonso/sapp/files/10980879/file.4.pdf)

I attempted to create a sample PDF, but in the actual scenario, I am using the DOMPDF library to generate the PDF.

**Comment by parallels999** [comment]
> I found that there is a "Digest Mismatch" error

I can't find that, it comes out correct, just **The certificate is not trusted because the issuer certificate is unknown**

**Comment by Abdulazeezvp** [comment]
I got response mentioned, in linux pdfsig command.

**Comment by parallels999** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=99365
> There is alos "Digest mismatch" though, which also says something about whether the document was been modified.
> As I understand it you basically have three booleans:
>
>1. does the digest for the file match that in the signature dictionary?
>2. does the signature in the dictionary sign the digest?
>3. **is the signature trusted?**
>
>And to lessen the confusion maybe these three cases should attempt to
not use overlapping terminology. I'm new to this certificate validation
things though, so maybe it's just me being confused because I'm not yet
clued in on the details. :)

The problem seems the same as I mentioned initially, the signature is correct
>just The certificate is not trusted because the issuer certificate is unknown

https://fossies.org/linux/poppler/utils/pdfsig.cc

**Comment by parallels999** [comment]
@dealfonso must be closed
