### ISSUE TITLE
error happened

### ISSUE THREAD

**Issue by herzhy** [dealfonso/sapp#5]
Dear MR Alfonso
Excuse me again , How can I solve the problem like this in picture? and because of what it can be happened

thanks before for your attention

![image](https://user-images.githubusercontent.com/89023605/130233498-44c85af2-dce5-4c1b-bc95-1566767c1a56.png)

**Comment by dealfonso** [comment]
Sorry but that problem is not related to sapp.

Please use Google... E.g. a quick search... https://stackoverflow.com/questions/30638754/fatal-error-class-finfo-not-found-in-c-xampp-htdocs-portfolio-actions-addpro

**Comment by herzhy** [comment]
Okay Mr AlfonsoThank you and I’m Sorry for that Sent from Mail for Windows From: Carlos de AlfonsoSent: 20 August 2021 20:30To: dealfonso/sappCc: herzhy; AuthorSubject: Re: [dealfonso/sapp] error happened (#5) Sorry but that problem is not related to sapp.Please use Google... E.g. a quick search... https://stackoverflow.com/questions/30638754/fatal-error-class-finfo-not-found-in-c-xampp-htdocs-portfolio-actions-addpro—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
