### ISSUE TITLE
Uninterpreted pdf

### ISSUE THREAD

**Issue by Lucas-mendes19** [dealfonso/sapp#56]
in my use of the library I found a pdf that it is not being possible to sign and that is not even getting past the interpretation of the content. Follow the pdf for maybe future improvements, testing and corrections.

[YN9qRfBknKDKR4axgFGVD2DJsMZzgNZQQqafhHOv.pdf](https://github.com/dealfonso/sapp/files/12080941/YN9qRfBknKDKR4axgFGVD2DJsMZzgNZQQqafhHOv.pdf)

**Comment by dealfonso** [comment]
hi, I'll take a lot. Thank you!
