### ISSUE TITLE
Certificate chain not included in signature.

### ISSUE THREAD

**Issue by hidasw** [dealfonso/sapp#65]
Trying to signing pdf with pkcs12 (CA chain included). But in the signed pdf result, theres no chain certificate shown, just single signer certificate shown.
Is there additional options or parameters to include chain certificates?

**Comment by erikn69** [comment]
Maybe #61 ???

**Comment by dealfonso** [comment]
hi, #61 is supposed to give that option. Please test it and let me know

**Comment by hidasw** [comment]
yes its works.
