### ISSUE TITLE
__SIGNATURE_MAX_LENGTH already defined when using multiple PDFDoc objects in the same script.

### ISSUE THREAD

**Issue by Jacq** [dealfonso/sapp#74]
Defining constant __SIGNATURE_MAX_LENGTH in PDFDoc.php: 
https://github.com/dealfonso/sapp/blob/37ff2659d88dc1f9a8c6a2cf22f6319c437c7934/src/PDFDoc.php#L469

, causes a error constant already defined when using the library to sign multiple times a document. The constant is created during the first sign. I suppose that this __SIGNATURE_MAX_LENGTH depends of signature_data parameters so should be move to a protected parameter instead of a global constant?

Thanks!

Jacq

**Comment by dealfonso** [comment]
yes, I think it is a good idea. Are you willing to contribute to sapp?

**Comment by Jacq** [comment]
It looks that @erikn69 has done it already, thanks!
