### ISSUE TITLE
UTF-8 Support

### ISSUE THREAD

**Issue by krupong** [dealfonso/sapp#78]
I am testing the signature -> set_metadata_props  feature , but it's not show correctly.
My signing reason is "ทดสอบ" 

![Screenshot_20240729_143316](https://github.com/user-attachments/assets/153457a2-7145-4e36-b3a5-cecbecd7a251)

Is it support utf-8 encoding?
Thank you.

**Comment by erikn69** [comment]
Try #79

**Comment by erikn69** [comment]
>So I've change from :
`return "\xFE\xFF" . mb_convert_encoding($string, 'UTF-16BE', $encoding); `
TO :
`return "\xEF\xBB\xBF".mb_convert_encoding($string, 'UTF-8', $encoding);`

with that change I get this

![image](https://github.com/user-attachments/assets/0fc2f798-bba8-45ea-9f23-9d84b9f0d751)

**Comment by erikn69** [comment]
>What about using a custom encoded string when setting the metadata?

That would work, but there would be the problem that every time someone doesn't know that they should do their own encoding, they will have problems and open a new issue.

**Comment by erikn69** [comment]
@dealfonso One question, if the file says ANSI in the encoding, and the reason is in UTF-8 or another encoding, wouldn't this problem occur?

Look, I sent UTF-8 and it doesn't work
```
/Reason(ï»¿à¸ à¸²à¸©à¸²à¹„à¸—à¸¢)/Location(ï»¿sdfs Ã³ Ã­ Ã­)>>
```

But I did send ISO-8859-1
```
/Reason(ó í í {} ` ~)/Location(sdfs ó í í)>>
```

**Comment by erikn69** [comment]
>It considers that the encoding depends on the font, and depending on the font, the same character will show a representation or another

But on text contents, metadata don't use fonts

**Comment by erikn69** [comment]
I did try FPDF, and it works with UTF-8,
```
/Keywords (þÿ Ì + ^ ì ò Ò ê)
```
But here doesn't work
https://github.com/Setasign/FPDF/blob/0838e0ee4925716fcbbc50ad9e1799b5edfae0a0/fpdf.php#L1169C1-L1189C2

**Comment by krupong** [comment]
I try to sign with TCPDF, It work with UTF-8 too.
When open in VS-Code : 

![ภาพถ่ายหน้าจอ 2567-07-31 เวลา 11 24 39](https://github.com/user-attachments/assets/465a6809-b4fb-427b-930d-768b8bf2f894)

Sign with sapp, seem store as plain text : 
![ภาพถ่ายหน้าจอ 2567-07-31 เวลา 11 30 07](https://github.com/user-attachments/assets/d408aa57-5915-4818-b6de-337d993624f4)

**Comment by krupong** [comment]
I try [#79 ] and Convert metadata  to UTF-16BE with BOM, everthing is OK.

Problem is, when I set string contain  "\x0E\x28 " or "\x0E\x29" metadata is broken.
I think that when encode to PDF, there will be "(" or ")" in compiled charactor, causing the incorrect display.

For example, I set my string to "ภาษาไทย".
![ภาพ](https://github.com/user-attachments/assets/b1ee5968-9ca2-4c4d-aee2-6946f648d36b)

Will show like this:
![ภาพ](https://github.com/user-attachments/assets/ad620cf0-caaf-4d40-854a-1581eabb5cf3)

I do dirty fixed by adding "(" or ")" at the begining or end of string.
So I add "(" to beginning of "ภาษาไทย" like this -> "(ภาษาไทย".
![ภาพ](https://github.com/user-attachments/assets/6e6c5358-822a-4ea7-ab08-cba503fa19a5)

Then my signature show like this:
![ภาพ](https://github.com/user-attachments/assets/713054a1-470c-4ad5-a9eb-221a90053003)

It display the text correctly but still has "(" in front of it.

Is there a correct way to deal with this problem?

Thank you.

**Comment by angeljqv** [comment]
Feel free to make a PR with the fix 👍

**Comment by krupong** [comment]
Could you please check #84 

Thank you.

**Comment by dealfonso** [comment]
merged
