### ISSUE TITLE
LTV and timestamp

### ISSUE THREAD

**Issue by pakuningratan** [dealfonso/sapp#8]
how to add Timestamp and LTV support

**Comment by dealfonso** [comment]
Hi, sorry but it is not possible at this moment.

**Comment by ximo1984** [comment]
Hi,

Maybe this could help to add LTV and timestamp to the document:
https://github.com/hablutzel1/phpcmstimestamper

**Comment by dealfonso** [comment]
Thank you... I'll have a look. Anyway I have researched a bit and I think that I am on the way... the problem is to get time to develop the new features.

**Comment by MisterDuval** [comment]
any update?

**Comment by dealfonso** [comment]
Hi,
I'm sorry, but I'm still short of time to be able to do it.

**Comment by parallels999** [comment]
@MisterDuval also you could make a PR to make it possible

**Comment by parallels999** [comment]
@pakuningratan @MisterDuval, what about #52?

**Comment by erikn69** [comment]
Just a note to anyone interested in implementing LTV:
 
This is where that starts: [https://www.etsi.org/ts_10277804v010101p.pdf](https://www.etsi.org/deliver/etsi_ts/102700_102799/10277804/01.01.01_60/ts_10277804v010101p.pdf)

**Comment by hidasw** [comment]
implement in [https://github.com/dealfonso/sapp/pull/70](url)
check it out.

**Comment by dealfonso** [comment]
pr #70 solves this issue. Thank you for your work!
