### ISSUE TITLE
Setting producer PDF/A Conformance

### ISSUE THREAD

**Issue by krupong** [dealfonso/sapp#82]
My original pdf when open with Acrobat reader it's look like this.

![ภาพถ่ายหน้าจอ 2567-09-09 เวลา 12 42 50](https://github.com/user-attachments/assets/435ecf24-0b4b-4a7e-a849-bf45b7ffc9b5)

After sign : 
![ภาพถ่ายหน้าจอ 2567-09-09 เวลา 12 42 28](https://github.com/user-attachments/assets/1b78cdc3-92fa-4ea2-99f4-bdbea8af2f81)

By comment out $info_obj["Producer"] it work correctly.

**Comment by dealfonso** [comment]
Could you please try this quick-and-dirty modification?
```php
$info_obj["Producer"] = new PDFValueString("Modificado con SAPP");
```

**Comment by krupong** [comment]
> Could you please try this quick-and-dirty modification?
> 
> ```
> $info_obj["Producer"] = new PDFValueString("Modificado con SAPP");
> ```

Problem solved.
Thank you.

**Comment by dealfonso** [comment]
I have updated the patch into the main branch
