### ISSUE TITLE
Posição da assinatura

### ISSUE THREAD

**Issue by krefects** [dealfonso/sapp#9]
é possivel inserir a assinatura em uma posição da pagina?  
$x
$y

tentei da forma abaixo mais nao funcionou para duas assinaturas, elas ficam em cima uma da outra.
$obj->set_signature_appearance($page,[120,60, $position_sig['y'], $position_sig['x']]);

**Comment by dealfonso** [comment]
hi,

yes, it is possible... the rectangle position must be specified as [x, y, size_x, size_y]. From your example, it seems that you have swapped position, size and coordinates. I think that it should be `$obj->set_signature_appearance($page, [ $position_sig['x'], $position_sig['y'], 60, 120 ]); `

-- Carlos

**Comment by krefects** [comment]
Obrigado pela resposta.
eu tentei posicionar da forma sugerida, porem ao adicionar a posição y e x, altera-se também o tamanho do bloco.
não consigo uma forma de deixar o bloco de tamanho fixo e mudar apenas a posição.

![Sem título](https://user-images.githubusercontent.com/17180773/134804968-3795778c-f657-49a0-bf92-0476703a98ef.png)
